# Generated by Django 5.2.7 on 2025-11-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_transaction_visible_by_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='platform_access',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='support',
        ),
        migrations.RemoveField(
            model_name='client',
            name='template',
        ),
    ]
