# Generated by Django 5.2.7 on 2025-11-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_client_unnecessary_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='annual_household_income',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='csl',
        ),
        migrations.RemoveField(
            model_name='client',
            name='current_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='client',
            name='experience_comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='invested_capital',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ldd',
        ),
        migrations.RemoveField(
            model_name='client',
            name='life_insurance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='livret_ab',
        ),
        migrations.RemoveField(
            model_name='client',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='client',
            name='objectives_comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pea',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='professional_activity_comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='professional_activity_status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='professions',
        ),
        migrations.RemoveField(
            model_name='client',
            name='professions_comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='savings_comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='securities_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_optimization',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_optimization_comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_wealth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='trading_portfolio',
        ),
    ]
