# Generated by Django 5.2.7 on 2025-11-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_client_patrimonial_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientAsset',
        ),
        migrations.DeleteModel(
            name='ClientRIB',
        ),
        migrations.DeleteModel(
            name='ClientUsefulLink',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='RIB',
        ),
        migrations.DeleteModel(
            name='UsefulLink',
        ),
    ]
