# Generated by Django 5.2.7 on 2025-11-14 08:54

import django.db.models.deletion
from django.db import migrations, models


def create_roles_from_existing_data(apps, schema_editor):
    """Create Role objects from existing UserDetails role strings"""
    Role = apps.get_model('api', 'Role')
    UserDetails = apps.get_model('api', 'UserDetails')
    
    # Get all unique role values from UserDetails (still CharField at this point)
    existing_roles = set()
    for user_detail in UserDetails.objects.all():
        role_value = getattr(user_detail, 'role', '0') or '0'
        if role_value and role_value not in existing_roles:
            existing_roles.add(role_value)
    
    # Create Role objects for each unique role value
    for role_value in existing_roles:
        if role_value:  # Skip empty strings
            # Map common role values to names
            role_name_map = {
                '0': 'User',
                'admin': 'Admin',
                'teamleader': 'Team Leader',
                'gestionnaire': 'Gestionnaire',
            }
            role_name = role_name_map.get(role_value.lower(), role_value.capitalize())
            
            # Check if role already exists (by name)
            if Role.objects.filter(name__iexact=role_name).exists():
                continue
            
            # Determine data_access based on role
            if role_value.lower() == 'admin':
                data_access = 'all'
            elif role_value.lower() == 'teamleader':
                data_access = 'team_only'
            else:
                data_access = 'own_only'
            
            # Generate role ID
            import uuid
            role_id = uuid.uuid4().hex[:12]
            while Role.objects.filter(id=role_id).exists():
                role_id = uuid.uuid4().hex[:12]
            
            Role.objects.create(
                id=role_id,
                name=role_name,
                data_access=data_access
            )


def migrate_userdetails_roles_to_foreignkey(apps, schema_editor):
    """Update UserDetails to use Role ForeignKey - migrate from CharField to ForeignKey"""
    Role = apps.get_model('api', 'Role')
    UserDetails = apps.get_model('api', 'UserDetails')
    
    # Create mapping from old role strings to Role objects
    role_mapping = {}
    for role in Role.objects.all():
        role_name_lower = role.name.lower()
        # Map role names back to original string values
        if role_name_lower == 'admin':
            role_mapping['admin'] = role
        elif 'leader' in role_name_lower or role_name_lower == 'team leader':
            role_mapping['teamleader'] = role
        elif 'gestionnaire' in role_name_lower:
            role_mapping['gestionnaire'] = role
        else:
            role_mapping['0'] = role
            role_mapping[''] = role
    
    # Update each UserDetails record
    for user_detail in UserDetails.objects.all():
        old_role_value = getattr(user_detail, 'role', '0') or '0'
        role_obj = role_mapping.get(old_role_value) or role_mapping.get('0')
        if role_obj:
            user_detail.role_id_temp = role_obj
            user_detail.save(update_fields=['role_id_temp'])


def migrate_roles_reverse(apps, schema_editor):
    """Reverse migration - convert Role objects back to strings"""
    # This would require storing the original role string, which we don't have
    # So we'll just set a default
    UserDetails = apps.get_model('api', 'UserDetails')
    UserDetails.objects.all().update(role='0')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_asset_rib_usefullink_transaction_models'),
    ]

    operations = [
        # Step 1: Add data_access to Role and create new models
        migrations.AddField(
            model_name='role',
            name='data_access',
            field=models.CharField(choices=[('all', 'All'), ('team_only', 'Team Only'), ('own_only', 'Own Only')], default='own_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client')], default='lead', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('component', models.CharField(default='', max_length=100)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client')], default='lead', max_length=10)),
                ('can_read', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='api.status')),
            ],
            options={
                'unique_together': {('component', 'field_name', 'type', 'status')},
            },
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='api.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='api.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        # Step 2: Create roles from existing data BEFORE changing the field
        migrations.RunPython(create_roles_from_existing_data, migrations.RunPython.noop),
        # Step 3: Add temporary role_id field (ForeignKey)
        migrations.AddField(
            model_name='userdetails',
            name='role_id_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_temp', to='api.role', db_column='role_id_temp'),
        ),
        # Step 4: Migrate data from role (CharField) to role_id_temp (ForeignKey)
        migrations.RunPython(migrate_userdetails_roles_to_foreignkey, migrations.RunPython.noop),
        # Step 5: Remove old role CharField
        migrations.RemoveField(
            model_name='userdetails',
            name='role',
        ),
        # Step 6: Rename role_id_temp to role
        migrations.RenameField(
            model_name='userdetails',
            old_name='role_id_temp',
            new_name='role',
        ),
    ]
