# Generated by Django 5.2.7 on 2025-11-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_userdetails_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.CharField(blank=True, choices=[('lead', 'Lead'), ('client', 'Client')], max_length=10, null=True),
        ),
    ]
