# Generated by Django 5.2.7 on 2025-11-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_make_permission_fields_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('component', 'field_name', 'status')},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='type',
        ),
    ]
