# Generated by Django 5.2.7 on 2025-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_type_from_permission'),
    ]

    operations = [
        # First, remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
        # Add the new action field
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=10),
        ),
        # Remove old boolean fields
        migrations.RemoveField(
            model_name='permission',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_read',
        ),
        # Finally, add new unique_together constraint with action field
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('component', 'field_name', 'action', 'status')},
        ),
    ]
