# Generated by Django 5.2.7 on 2025-11-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_add_create_delete_actions_to_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='clientId',
        ),
        migrations.RemoveField(
            model_name='note',
            name='clientId',
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact')], default='lead', max_length=10),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('civility', models.CharField(blank=True, default='', max_length=10)),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('successor', models.CharField(blank=True, default='', max_length=200)),
                ('managed_by', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contactId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contact'),
        ),
        migrations.AddField(
            model_name='note',
            name='contactId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contact'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
