# Generated by Django 5.2.7 on 2025-11-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_rename_role_to_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_confirmateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_teleoperateur',
            field=models.BooleanField(default=False),
        ),
    ]
