# Generated by Django 5.2.7 on 2025-11-17 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_add_source_and_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='confirmer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='note',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='successor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='team',
        ),
        migrations.AddField(
            model_name='contact',
            name='confirmateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmateur_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
