# Generated by Django 5.2.7 on 2025-11-17 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_contact_id_creator_id_to_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('CNI', 'CNI'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('SELFIE', 'Selfie'), ('RIB', 'RIB')], max_length=50)),
                ('has_document', models.BooleanField(default=False)),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.contact')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contact_id', 'document_type')},
            },
        ),
    ]
