# Generated by Django 5.2.7 on 2025-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_add_document_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('lead', 'Lead'), ('contact', 'Contact'), ('client', 'Client')], default='lead', max_length=10),
        ),
    ]
