# Generated by Django 5.2.7 on 2025-11-20 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_client_status_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('smtp_server', models.CharField(default='', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(default='', max_length=255)),
                ('smtp_password', models.CharField(default='', max_length=255)),
                ('imap_server', models.CharField(blank=True, default='', max_length=255)),
                ('imap_port', models.IntegerField(blank=True, default=993, null=True)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('email_address', models.EmailField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('email_type', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('draft', 'Draft')], default='sent', max_length=10)),
                ('subject', models.CharField(default='', max_length=500)),
                ('from_email', models.EmailField(default='', max_length=255)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('bcc_emails', models.JSONField(blank=True, default=list)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('message_id', models.CharField(blank=True, default='', max_length=500)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=500)),
                ('references', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='api.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'email_type', '-sent_at'], name='api_email_user_id_f90709_idx'), models.Index(fields=['user', 'is_read'], name='api_email_user_id_847816_idx')],
            },
        ),
    ]
