# Generated by Django 5.2.7 on 2025-11-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_emailsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignature',
            name='logo_position',
            field=models.CharField(blank=True, choices=[('top', 'En haut'), ('bottom', 'En bas'), ('left', 'À gauche'), ('right', 'À droite')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='emailsignature',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
