# Generated by Django 5.2.7 on 2025-11-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_update_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('color', models.CharField(blank=True, default='#3b82f6', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_user_id_48bbdc_idx',
            old_name='api_notific_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_user_id_16328d_idx',
            old_name='api_notific_user_id_is_read_idx',
        ),
        migrations.AddField(
            model_name='note',
            name='categ_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='api.notecategory'),
        ),
    ]
