# Generated by Django 5.2.7 on 2025-11-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_notecategory_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecategory',
            name='color',
        ),
    ]
