# Generated by Django 5.2.7 on 2025-11-25 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_color_from_notecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['contactId', '-created_at'], name='api_note_contact_b6d266_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['categ_id', '-created_at'], name='api_note_categ_i_8c8197_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['userId', '-created_at'], name='api_note_userId__ed24cf_idx'),
        ),
    ]
