# Generated by Django 5.2.7 on 2025-11-26 11:31

from django.db import migrations, models


def migrate_phone_fields(apps, schema_editor):
    """Convert phone fields from CharField to BigIntegerField
    
    NOTE: Due to PostgreSQL trigger constraints, this migration may need to be run manually.
    See migrate_phone_to_integer.sql for the SQL script to run directly in the database.
    """
    # Use raw SQL to handle the migration
    # This avoids issues with Django ORM and PostgreSQL constraints
    with schema_editor.connection.cursor() as cursor:
        # Step 1: Drop NOT NULL constraints if they exist
        try:
            cursor.execute("ALTER TABLE api_contact ALTER COLUMN phone DROP NOT NULL;")
        except Exception:
            pass  # Constraint might not exist
        
        try:
            cursor.execute("ALTER TABLE api_contact ALTER COLUMN mobile DROP NOT NULL;")
        except Exception:
            pass  # Constraint might not exist
        
        try:
            cursor.execute("ALTER TABLE api_userdetails ALTER COLUMN phone DROP NOT NULL;")
        except Exception:
            pass  # Constraint might not exist
        
        # Step 2: Set empty strings to NULL
        cursor.execute("UPDATE api_contact SET phone = NULL WHERE phone = '' OR phone = ' ' OR phone IS NULL;")
        cursor.execute("UPDATE api_contact SET mobile = NULL WHERE mobile = '' OR mobile = ' ' OR mobile IS NULL;")
        cursor.execute("UPDATE api_userdetails SET phone = NULL WHERE phone = '' OR phone = ' ' OR phone IS NULL;")
        
        # Step 3: Change column types to bigint
        # PostgreSQL will automatically convert valid numeric strings to integers
        # Use single-line SQL to avoid potential parsing issues
        cursor.execute("ALTER TABLE api_contact ALTER COLUMN phone TYPE bigint USING CASE WHEN phone ~ '^[0-9]+$' THEN phone::bigint ELSE NULL END;")
        
        cursor.execute("ALTER TABLE api_contact ALTER COLUMN mobile TYPE bigint USING CASE WHEN mobile ~ '^[0-9]+$' THEN mobile::bigint ELSE NULL END;")
        
        cursor.execute("ALTER TABLE api_userdetails ALTER COLUMN phone TYPE bigint USING CASE WHEN phone ~ '^[0-9]+$' THEN phone::bigint ELSE NULL END;")


def reverse_convert(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_clear_phone_numbers'),
    ]

    operations = [
        # Do everything in one Python function to avoid trigger issues
        # The RunPython will handle the actual database schema changes
        migrations.RunPython(migrate_phone_fields, reverse_convert),
        # Update Django's model state to reflect the change
        # These AlterField operations only update Django's internal state,
        # they don't modify the database (since RunPython already did that)
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
