# Generated by Django 5.2.7 on 2025-11-26 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_change_phone_to_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['teleoperator_id', '-created_at'], name='api_contact_teleope_0d6826_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['confirmateur_id', '-created_at'], name='api_contact_confirm_e23bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['creator_id', '-created_at'], name='api_contact_creator_04f519_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status_id', '-created_at'], name='api_contact_status__9d2dab_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['source_id', '-created_at'], name='api_contact_source__0d924f_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['fname', 'lname'], name='api_contact_fname_2bab77_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='api_contact_email_dacaca_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='api_contact_phone_67148b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['mobile'], name='api_contact_mobile_7b0f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-created_at'], name='api_contact_created_b984ff_idx'),
        ),
    ]
