# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models
import uuid


def create_default_preferences_for_existing_roles(apps, schema_editor):
    """Create default notification preferences for all existing roles"""
    Role = apps.get_model('api', 'Role')
    NotificationPreference = apps.get_model('api', 'NotificationPreference')
    
    for role in Role.objects.all():
        # Check if preference already exists
        if not NotificationPreference.objects.filter(role=role).exists():
            # Generate a unique ID
            pref_id = uuid.uuid4().hex[:12]
            while NotificationPreference.objects.filter(id=pref_id).exists():
                pref_id = uuid.uuid4().hex[:12]
            
            NotificationPreference.objects.create(
                id=pref_id,
                role=role,
                notify_message_received=True,
                notify_sensitive_contact_modification=True,
                notify_contact_edit=True
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_add_created_by_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('notify_message_received', models.BooleanField(default=True)),
                ('notify_sensitive_contact_modification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='api.role')),
            ],
            options={
                'unique_together': {('role',)},
            },
        ),
        migrations.RunPython(create_default_preferences_for_existing_roles),
    ]

