# Generated by Django 5.2.7

from django.db import migrations, models


def set_default_notify_contact_edit(apps, schema_editor):
    """Set notify_contact_edit to True for all existing preferences"""
    NotificationPreference = apps.get_model('api', 'NotificationPreference')
    NotificationPreference.objects.all().update(notify_contact_edit=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_notification_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_contact_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_default_notify_contact_edit),
    ]

