# Generated by Django 5.2.7 on 2025-12-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_add_notify_contact_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosseSettings',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('forced_columns', models.JSONField(blank=True, default=list)),
                ('forced_filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fosse_settings', to='api.role')),
            ],
            options={
                'unique_together': {('role',)},
            },
        ),
    ]
