# Generated by Django 5.2.7 on 2025-12-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_fosse_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossesettings',
            name='default_order',
            field=models.CharField(choices=[('default', 'Par défaut (date de création)'), ('random', 'Aléatoire')], default='default', max_length=20),
        ),
    ]
