# Generated by Django 5.2.7 on 2025-12-08 10:57

from django.db import migrations, models


def migrate_random_to_alphabetic(apps, schema_editor):
    """Migrate existing 'random' values to 'alphabetic'"""
    FosseSettings = apps.get_model('api', 'FosseSettings')
    FosseSettings.objects.filter(default_order='random').update(default_order='alphabetic')


def reverse_migration(apps, schema_editor):
    """Reverse migration - change 'alphabetic' back to 'random'"""
    FosseSettings = apps.get_model('api', 'FosseSettings')
    FosseSettings.objects.filter(default_order='alphabetic').update(default_order='random')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_add_default_order_to_fosse_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossesettings',
            name='default_order',
            field=models.CharField(choices=[('default', 'Par défaut (date de création)'), ('alphabetic', 'Ordre alphabétique'), ('id_order', 'Ordre par ID')], default='default', max_length=20),
        ),
        migrations.RunPython(migrate_random_to_alphabetic, reverse_migration),
    ]
