# Generated by Django 5.2.7 on 2025-12-08 11:31

from django.db import migrations, models


def convert_old_order_values(apps, schema_editor):
    """Convert old order values to new ones"""
    FosseSettings = apps.get_model('api', 'FosseSettings')
    # Convert 'alphabetic' and 'id_order' to 'default' (full name ordering)
    for setting in FosseSettings.objects.filter(default_order__in=['alphabetic', 'id_order']):
        setting.default_order = 'default'
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_change_order_choices_in_fosse_settings'),
    ]

    operations = [
        migrations.RunPython(convert_old_order_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fossesettings',
            name='default_order',
            field=models.CharField(choices=[('default', 'Par défaut (nom complet)'), ('created_at_asc', 'Date de création (ancien à nouveau)'), ('created_at_desc', 'Date de création (nouveau à ancien)'), ('updated_at_asc', 'Date de modification (ancien à nouveau)'), ('updated_at_desc', 'Date de modification (nouveau à ancien)'), ('email_asc', 'Email (ordre alphabétique)')], default='default', max_length=20),
        ),
    ]
