# Generated by Django 5.2.7 on 2025-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_update_fosse_settings_order_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]

