# Generated by Django 5.2.7 on 2025-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_add_is_admin_to_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_fosse_default',
            field=models.BooleanField(default=False),
        ),
    ]

