# Generated by Django 5.2.7 on 2025-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_add_is_fosse_default_to_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='is_admin',
            new_name='is_event',
        ),
    ]

