# Generated by Django 5.2.7 on 2025-12-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_rename_is_admin_to_is_event_in_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossesettings',
            name='default_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fosse_settings_default', to='api.status'),
        ),
    ]
