# Generated by Django 5.2.7 on 2025-12-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_add_default_status_to_fosse_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='client_default',
            field=models.BooleanField(default=False),
        ),
    ]

