# Generated by Django 5.2.7 on 2025-12-09 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_add_client_default_to_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contrat',
            field=models.CharField(blank=True, choices=[('CONTRAT SIGNÉ', 'CONTRAT SIGNÉ'), ('CONTRAT ENVOYÉ MAIS PAS SIGNÉ', 'CONTRAT ENVOYÉ MAIS PAS SIGNÉ'), ('PAS DE CONTRAT ENVOYÉ', 'PAS DE CONTRAT ENVOYÉ'), ("J'AI SIGNÉ LE CONTRAT POUR LE CLIENT", "J'AI SIGNÉ LE CONTRAT POUR LE CLIENT")], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_pro_tr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='montant_encaisse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='nom_de_scene',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='paiement',
            field=models.CharField(blank=True, choices=[('carte', 'Carte'), ('virement', 'Virement')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='potentiel',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='produit',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='rib',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='api.platform'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['platform_id', '-created_at'], name='api_contact_platfor_f53a24_idx'),
        ),
    ]
