# Generated by Django 5.2.7 on 2025-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_contact_bonus_contact_contrat_contact_date_pro_tr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='rib',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hrex',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='fossesettings',
            name='default_order',
            field=models.CharField(choices=[('none', 'Non défini (personnalisable)'), ('created_at_asc', 'Date de création (ancien à nouveau)'), ('created_at_desc', 'Date de création (nouveau à ancien)'), ('updated_at_asc', 'Date de modification (ancien à nouveau)'), ('updated_at_desc', 'Date de modification (nouveau à ancien)'), ('email_asc', 'Email (ordre alphabétique)')], default='default', max_length=20),
        ),
    ]
