# Generated by Django 5.2.7 on 2025-12-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_add_hrex_to_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
