# Generated by Django 5.2.7 on 2025-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_add_otp_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
