# Generated by Django 5.2.7 on 2025-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_add_deleted_at_to_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='require_otp',
            field=models.BooleanField(default=False),
        ),
    ]
