# Generated by Django 5.2.7 on 2025-12-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_add_require_otp_to_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='confirmateur_email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='confirmateur_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
