# Generated by Django 5.2.7 on 2025-12-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_add_confirmateur_email_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='old_contact_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
