# Generated by Django 5.2.7 on 2025-12-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_add_old_contact_id_to_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='confirmateur_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='confirmateur_telephone',
        ),
    ]
