# Generated by Django 5.2.7 on 2025-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_contact_confirmateur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='old_logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
