# Generated by Django 5.2.7 on 2025-12-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_add_old_logs_to_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='creator_id',
        ),
    ]
