# Generated by Django 5.2.7 on 2025-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_creator_id_from_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='confirmateur_email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='confirmateur_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]

