# Generated by Django 5.2.7 on 2025-12-23 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_fossesettings_default_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['contact_id', 'event_type', '-created_at'], name='api_log_contact_ef18f7_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['event_type', '-created_at'], name='api_log_event_t_3dcca7_idx'),
        ),
    ]
