# Generated by Django 5.2.7 on 2025-12-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_alter_log_created_at_log_api_log_contact_ef18f7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='ip_whitelist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='ip_whitelist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]


