# Generated by Django 5.2.7 on 2025-12-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_add_ip_whitelist_to_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='autre_informations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
