# Generated by Django 5.2.7 on 2025-12-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_add_autre_informations_to_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_d_inscription',
            field=models.DateField(blank=True, null=True),
        ),
    ]
