# Generated by Django 5.2.7 on 2025-12-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_add_date_d_inscription_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_d_inscription',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
