# Generated by Django 5.2.7 on 2025-12-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_change_date_d_inscription_to_string'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Retrait', 'Retrait'), ('Depot', 'Depot')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['contact', '-date'], name='api_transac_contact_bbb24b_idx'), models.Index(fields=['contact', 'type', '-date'], name='api_transac_contact_b32d47_idx'), models.Index(fields=['status', '-date'], name='api_transac_status_6a6ca0_idx'), models.Index(fields=['-date'], name='api_transac_date_310220_idx')],
            },
        ),
    ]
