# Generated by Django 5.2.7 on 2025-12-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_transaction_bonus_transaction_platform_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('carte', 'Carte'), ('virement', 'Virement')], default='', max_length=20),
        ),
    ]
