# Generated by Django 5.2.7 on 2025-12-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_transaction_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('valid', 'Valid'), ('invalid', 'Invalid')], db_index=True, default='not_verified', max_length=20),
        ),
    ]
