# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_add_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_lead_to_client',
            field=models.DateField(blank=True, null=True),
        ),
    ]

