# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_add_date_lead_to_client_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_lead_to_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

