# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_change_date_lead_to_client_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossesettings',
            name='default_order',
            field=models.CharField(
                choices=[
                    ('none', 'Non défini (personnalisable)'),
                    ('created_at_asc', 'Date de création (ancien à nouveau)'),
                    ('created_at_desc', 'Date de création (nouveau à ancien)'),
                    ('updated_at_asc', 'Date de modification (ancien à nouveau)'),
                    ('updated_at_desc', 'Date de modification (nouveau à ancien)'),
                    ('assigned_at_asc', 'Date d\'attribution (ancien à nouveau)'),
                    ('assigned_at_desc', 'Date d\'attribution (nouveau à ancien)'),
                    ('date_lead_to_client_asc', 'Date de passage client (ancien à nouveau)'),
                    ('date_lead_to_client_desc', 'Date de passage client (nouveau à ancien)'),
                    ('email_asc', 'Email (ordre alphabétique)'),
                    ('random', 'Aléatoire'),
                ],
                default='none',
                max_length=30
            ),
        ),
    ]

