# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_add_date_lead_to_client_order_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('CNI', 'CNI'),
                    ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'),
                    ('SELFIE', 'Selfie'),
                    ('RIB', 'RIB'),
                    ('CONTRAT', 'Contrat'),
                ],
                max_length=50
            ),
        ),
    ]

