# Generated by Django 5.2.7 on 2026-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_add_contrat_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('failed', 'Échoué'), ('to_verify', 'A vérifier')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Retrait', 'Retrait'), ('Depot', 'Depot'), ('Ouverture', 'Ouverture')], max_length=20),
        ),
    ]
