# Generated by Django 5.2.7 on 2026-01-07 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_alter_transaction_status_alter_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactView',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_fosse', models.BooleanField(default=False)),
                ('search_term', models.CharField(blank=True, default='', max_length=500)),
                ('status_type', models.CharField(choices=[('all', 'All'), ('lead', 'Lead'), ('client', 'Client')], default='all', max_length=20)),
                ('order', models.CharField(default='created_at_desc', max_length=50)),
                ('items_per_page', models.IntegerField(default=50)),
                ('column_filters', models.JSONField(blank=True, default=dict)),
                ('visible_columns', models.JSONField(blank=True, default=list)),
                ('column_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_contact_user_id_805a60_idx'), models.Index(fields=['user', 'is_fosse', '-created_at'], name='api_contact_user_id_7f6eb4_idx')],
            },
        ),
    ]
