from django.urls import path
from . import views as api_views

urlpatterns = [
    # Notes endpoints
    path('notes/', api_views.NoteListCreateView.as_view(), name='note-list-create'),
    path('notes/create/', api_views.NoteListCreateView.as_view(), name='note-create'),
    path('notes/<str:pk>/update/', api_views.NoteUpdateView.as_view(), name='note-update'),
    path('notes/delete/<str:pk>/', api_views.NoteDeleteView.as_view(), name='note-delete'),
    # Contacts endpoints
    path('contacts/', api_views.ContactView.as_view(), name='contact-list'),
    path('contacts/fosse/', api_views.FosseContactView.as_view(), name='fosse-contact-list'),
    path('contacts/create/', api_views.contact_create, name='contact-create'),
    path('contacts/csv-import-preview/', api_views.csv_import_preview, name='csv-import-preview'),
    path('contacts/csv-import/', api_views.csv_import_contacts, name='csv-import-contacts'),
    path('contacts/<str:contact_id>/', api_views.contact_detail, name='contact-detail'),
    path('contacts/<str:contact_id>/delete/', api_views.contact_delete, name='contact-delete'),
    path('contacts/<str:contact_id>/logs/', api_views.contact_logs, name='contact-logs'),
    path('contacts/<str:contact_id>/documents/', api_views.contact_documents, name='contact-documents'),
    # Documents endpoints
    path('documents/upload/', api_views.document_upload, name='document-upload'),
    path('documents/create/', api_views.document_create, name='document-create'),
    path('documents/<str:document_id>/', api_views.document_update, name='document-update'),
    path('documents/<str:document_id>/delete/', api_views.document_delete, name='document-delete'),
    path('documents/<str:document_id>/download/', api_views.document_download, name='document-download'),
    path('documents/<str:document_id>/view-url/', api_views.document_view_url, name='document-view-url'),
    # Teams endpoints
    path('teams/', api_views.team_list, name='team-list'),
    path('teams/create/', api_views.team_create, name='team-create'),  # POST for create
    path('teams/<str:team_id>/', api_views.team_detail, name='team-detail'),
    path('teams/<str:team_id>/delete/', api_views.team_delete, name='team-delete'),
    path('teams/<str:team_id>/add-member/', api_views.team_add_member, name='team-add-member'),
    path('teams/<str:team_id>/remove-member/', api_views.team_remove_member, name='team-remove-member'),
    path('teams/<str:team_id>/set-leader/', api_views.team_set_leader, name='team-set-leader'),
    # Users endpoints
    path('user/current/', api_views.get_current_user, name='get-current-user'),
    path('users/', api_views.user_list, name='user-list'),
    path('users/create/', api_views.UserCreateView.as_view(), name='user-create'),
    path('users/<str:user_id>/', api_views.user_delete, name='user-delete'),
    path('users/<str:user_id>/update/', api_views.user_update, name='user-update'),
    path('users/<str:user_id>/toggle-active/', api_views.user_toggle_active, name='user-toggle-active'),
    path('users/<str:user_id>/reset-password/', api_views.user_reset_password, name='user-reset-password'),
    # Events endpoints
    path('events/', api_views.event_list, name='event-list'),
    path('events/create/', api_views.event_create, name='event-create'),
    path('events/<str:event_id>/update/', api_views.event_update, name='event-update'),
    path('events/<str:event_id>/', api_views.event_delete, name='event-delete'),
    # Roles endpoints
    path('roles/', api_views.role_list, name='role-list'),
    path('roles/create/', api_views.role_create, name='role-create'),
    path('roles/<str:role_id>/', api_views.role_update, name='role-update'),
    path('roles/<str:role_id>/delete/', api_views.role_delete, name='role-delete'),
    # Permissions endpoints
    path('permissions/', api_views.permission_list, name='permission-list'),
    path('permissions/create/', api_views.permission_create, name='permission-create'),
    path('permissions/<str:permission_id>/', api_views.permission_update, name='permission-update'),
    path('permissions/<str:permission_id>/delete/', api_views.permission_delete, name='permission-delete'),
    # Permission-Role endpoints
    path('permission-roles/', api_views.permission_role_list, name='permission-role-list'),
    path('permission-roles/create/', api_views.permission_role_create, name='permission-role-create'),
    path('permission-roles/<str:permission_role_id>/delete/', api_views.permission_role_delete, name='permission-role-delete'),
    # Statuses endpoints
    path('statuses/', api_views.status_list, name='status-list'),
    path('statuses/create/', api_views.status_create, name='status-create'),
    path('statuses/reorder/', api_views.status_reorder, name='status-reorder'),
    path('statuses/<str:status_id>/', api_views.status_update, name='status-update'),
    path('statuses/<str:status_id>/delete/', api_views.status_delete, name='status-delete'),
    # Sources endpoints
    path('sources/', api_views.source_list, name='source-list'),
    path('sources/create/', api_views.source_create, name='source-create'),
    path('sources/<str:source_id>/', api_views.source_update, name='source-update'),
    path('sources/<str:source_id>/delete/', api_views.source_delete, name='source-delete'),
    # Note Categories endpoints
    path('note-categories/', api_views.note_category_list, name='note-category-list'),
    path('note-categories/create/', api_views.note_category_create, name='note-category-create'),
    path('note-categories/reorder/', api_views.note_category_reorder, name='note-category-reorder'),
    path('note-categories/<str:category_id>/', api_views.note_category_update, name='note-category-update'),
    path('note-categories/<str:category_id>/delete/', api_views.note_category_delete, name='note-category-delete'),
    # Stats endpoint
    path('stats/', api_views.get_stats, name='stats'),
    # Email endpoints
    path('emails/smtp-config/', api_views.smtp_config, name='smtp-config'),
    path('emails/test-connection/', api_views.test_smtp_connection, name='test-smtp-connection'),
    path('emails/send/', api_views.send_email, name='send-email'),
    path('emails/fetch/', api_views.fetch_emails, name='fetch-emails'),
    path('emails/signatures/', api_views.email_signatures, name='email-signatures'),
    path('emails/signatures/upload-logo/', api_views.email_signature_logo_upload, name='email-signature-logo-upload'),
    path('emails/signatures/logo-presigned-url/', api_views.email_signature_logo_presigned_url, name='email-signature-logo-presigned-url'),
    path('emails/signatures/logo-proxy/<path:file_path>/', api_views.email_signature_logo_proxy, name='email-signature-logo-proxy'),
    path('emails/signatures/<str:signature_id>/', api_views.email_signature_detail, name='email-signature-detail'),
    path('emails/', api_views.email_list, name='email-list'),
    path('emails/<str:email_id>/update/', api_views.email_update, name='email-update'),
    path('emails/<str:email_id>/delete/', api_views.email_delete, name='email-delete'),
    path('emails/<str:email_id>/', api_views.email_detail, name='email-detail'),
    # Chat endpoints
    path('chat/rooms/', api_views.chat_rooms, name='chat-rooms'),
    path('chat/rooms/<str:chat_room_id>/', api_views.chat_room_detail, name='chat-room-detail'),
    path('chat/rooms/<str:chat_room_id>/messages/', api_views.chat_messages, name='chat-messages'),
    path('chat/rooms/<str:chat_room_id>/read/', api_views.mark_messages_read, name='mark-messages-read'),
    path('chat/users/', api_views.chat_users, name='chat-users'),
    # Notifications endpoints
    path('notifications/', api_views.notification_list, name='notification-list'),
    path('notifications/unread-count/', api_views.notification_unread_count, name='notification-unread-count'),
    path('notifications/<str:notification_id>/read/', api_views.notification_mark_read, name='notification-mark-read'),
    path('notifications/mark-all-read/', api_views.notification_mark_all_read, name='notification-mark-all-read'),
    # Notification Preferences endpoints
    path('notification-preferences/', api_views.notification_preference_list, name='notification-preference-list'),
    path('notification-preferences/<str:role_id>/', api_views.notification_preference_detail, name='notification-preference-detail'),
    path('notification-preferences/<str:role_id>/update/', api_views.notification_preference_update, name='notification-preference-update'),
]
