from django.urls import path
from . import views as api_views

urlpatterns = [
    # Notes endpoints
    path('notes/', api_views.NoteListCreateView.as_view(), name='note-list-create'),
    path('notes/delete/<str:pk>/', api_views.NoteDeleteView.as_view(), name='note-delete'),
    path('notes/create/', api_views.NoteListCreateView.as_view(), name='note-create'),
    # Contacts endpoints
    path('contacts/', api_views.ContactView.as_view(), name='contact-list'),
    path('contacts/create/', api_views.contact_create, name='contact-create'),
    path('contacts/csv-import-preview/', api_views.csv_import_preview, name='csv-import-preview'),
    path('contacts/csv-import/', api_views.csv_import_contacts, name='csv-import-contacts'),
    path('contacts/<str:contact_id>/', api_views.contact_detail, name='contact-detail'),
    path('contacts/<str:contact_id>/delete/', api_views.contact_delete, name='contact-delete'),
    path('contacts/<str:contact_id>/logs/', api_views.contact_logs, name='contact-logs'),
    path('contacts/<str:contact_id>/documents/', api_views.contact_documents, name='contact-documents'),
    # Documents endpoints
    path('documents/upload/', api_views.document_upload, name='document-upload'),
    path('documents/create/', api_views.document_create, name='document-create'),
    path('documents/<str:document_id>/', api_views.document_update, name='document-update'),
    path('documents/<str:document_id>/delete/', api_views.document_delete, name='document-delete'),
    path('documents/<str:document_id>/download/', api_views.document_download, name='document-download'),
    path('documents/<str:document_id>/view-url/', api_views.document_view_url, name='document-view-url'),
    # Teams endpoints
    path('teams/', api_views.team_list, name='team-list'),
    path('teams/create/', api_views.team_create, name='team-create'),  # POST for create
    path('teams/<str:team_id>/', api_views.team_detail, name='team-detail'),
    path('teams/<str:team_id>/delete/', api_views.team_delete, name='team-delete'),
    path('teams/<str:team_id>/add-member/', api_views.team_add_member, name='team-add-member'),
    path('teams/<str:team_id>/remove-member/', api_views.team_remove_member, name='team-remove-member'),
    path('teams/<str:team_id>/set-leader/', api_views.team_set_leader, name='team-set-leader'),
    # Users endpoints
    path('user/current/', api_views.get_current_user, name='get-current-user'),
    path('users/', api_views.user_list, name='user-list'),
    path('users/create/', api_views.UserCreateView.as_view(), name='user-create'),
    path('users/<str:user_id>/', api_views.user_delete, name='user-delete'),
    path('users/<str:user_id>/update/', api_views.user_update, name='user-update'),
    path('users/<str:user_id>/toggle-active/', api_views.user_toggle_active, name='user-toggle-active'),
    path('users/<str:user_id>/reset-password/', api_views.user_reset_password, name='user-reset-password'),
    # Events endpoints
    path('events/', api_views.event_list, name='event-list'),
    path('events/create/', api_views.event_create, name='event-create'),
    path('events/<str:event_id>/update/', api_views.event_update, name='event-update'),
    path('events/<str:event_id>/', api_views.event_delete, name='event-delete'),
    # Roles endpoints
    path('roles/', api_views.role_list, name='role-list'),
    path('roles/create/', api_views.role_create, name='role-create'),
    path('roles/<str:role_id>/', api_views.role_update, name='role-update'),
    path('roles/<str:role_id>/delete/', api_views.role_delete, name='role-delete'),
    # Permissions endpoints
    path('permissions/', api_views.permission_list, name='permission-list'),
    path('permissions/create/', api_views.permission_create, name='permission-create'),
    path('permissions/<str:permission_id>/', api_views.permission_update, name='permission-update'),
    path('permissions/<str:permission_id>/delete/', api_views.permission_delete, name='permission-delete'),
    # Permission-Role endpoints
    path('permission-roles/', api_views.permission_role_list, name='permission-role-list'),
    path('permission-roles/create/', api_views.permission_role_create, name='permission-role-create'),
    path('permission-roles/<str:permission_role_id>/delete/', api_views.permission_role_delete, name='permission-role-delete'),
    # Statuses endpoints
    path('statuses/', api_views.status_list, name='status-list'),
    path('statuses/create/', api_views.status_create, name='status-create'),
    path('statuses/reorder/', api_views.status_reorder, name='status-reorder'),
    path('statuses/<str:status_id>/', api_views.status_update, name='status-update'),
    path('statuses/<str:status_id>/delete/', api_views.status_delete, name='status-delete'),
    # Sources endpoints
    path('sources/', api_views.source_list, name='source-list'),
    path('sources/create/', api_views.source_create, name='source-create'),
    path('sources/<str:source_id>/', api_views.source_update, name='source-update'),
    path('sources/<str:source_id>/delete/', api_views.source_delete, name='source-delete'),
    # Stats endpoint
    path('stats/', api_views.get_stats, name='stats'),
]
